#!/usr/bin/env bash
#
# osx-defaults
#
# Set reasonable MacOS defaults.
#
# Thanks to Mathias Bynens' MacOS defaults script:
# - https://github.com/mathiasbynens/dotfiles/blob/master/.osx

PROG=${0##*/}

# MacOS only...
if [[ $(uname) != "Darwin" ]]
then
  echo "$PROG script is for MacOS only!"
  exit 1
fi

# MacOS version check
if ! [[ $(sw_vers -productVersion) =~ ^10\.12\..+ ]]
then
  echo "$PROG script is intended for MacOS versions 10.11.x"
  exit 1
fi

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Accept XCode license
sudo xcodebuild -license accept

# Init rbenv
rbenv init

# Security
# ----------------------------------------------------------------------------

# Disable Gatekeeper
# Allows installing apps from anywhere
sudo spctl --master-disable

# Ask for password on screensaver
defaults write com.apple.screensaver askForPassword -bool true

# Require password immediately after sleep
defaults write com.apple.screensaver askForPasswordDelay 0

#set the screen saver delay in seconds, 600 = 10 minutes
defaults -currentHost write com.apple.screensaver idleTime 600

# Sharing
# ----------------------------------------------------------------------------

# Set computer name (as done via System Preferences → Sharing)
sudo scutil --set ComputerName "Fuzza"
sudo scutil --set HostName "Fuzza"
sudo scutil --set LocalHostName "Fuzza"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "Fuzza"

# General
# ----------------------------------------------------------------------------

# Set Sidebar icon size to small.
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -integer 1

# Save new documents to disk (not to iCloud) (default: not set).
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -boolean false

# Report computer name, MacOS version and IP address when clicking the clock
# in the Login window (default: not set).
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# Keyboard

# Toggle keyboard to use F1 as a functional keys without fn
sudo defaults write -g com.apple.keyboard.fnState -bool true

# Desktop & Screen Saver
# ----------------------------------------------------------------------------

# Disable shadows on screen captures (default: not set).
defaults write com.apple.screencapture disable-shadow -boolean true

# Disable useless dashboard
defaults write com.apple.dashboard mcx-disabled -boolean true

# Energy
# ----------------------------------------------------------------------------

# Set display sleep time on battery
sudo pmset -b displaysleep 5

# Disable system sleep on charger
sudo pmset -c sleep 0

# Show battery level in percents in menu bar
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

# Dock
# ----------------------------------------------------------------------------

# Minimize windows using the "Scale" effect.
defaults write com.apple.dock mineffect scale

# Reduce dock autohide time
defaults write com.apple.dock autohide-delay -int 0
defaults write com.apple.dock autohide-time-modifier -float 0.4

# Don’t automatically rearrange Mission control spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Finder
# ----------------------------------------------------------------------------

# Set default Finder location to home folder (~/)
defaults write com.apple.finder NewWindowTarget -string "PfLo" && \
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}"

# Show status bar.
defaults write com.apple.finder ShowStatusBar -bool true

# Show path bar.
defaults write com.apple.finder ShowPathbar -bool true

# Don't show icons on Desktop
defaults write com.apple.finder CreateDesktop -bool false

# Terminal
# ----------------------------------------------------------------------------

# Add terminal profiles for the Solarized Dark and Solarized Light color
# schemes.
open "../terminal/Solarized Dark.terminal"
sleep 1
open "../terminal/Solarized Light.terminal"
sleep 1

# Make Solarized Light the default terminal profile.
defaults write com.apple.Terminal "Default Window Settings" -string "Solarized Dark"
defaults write com.apple.Terminal "Startup Window Settings" -string "Solarized Dark"

# Other
# ----------------------------------------------------------------------------

# Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -int 0

# Avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Disable disk image verification
defaults write com.apple.frameworks.diskimages skip-verify -bool true && \
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true && \
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

# Disable annoying "are you sure you want to open it" messages
defaults write com.apple.LaunchServices LSQuarantine -bool NO

# XCode
# ----------------------------------------------------------------------------
defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES

###############################################################################
# Kill affected applications                                                  #
###############################################################################

for app in "Dock" "Terminal" \
  "Finder"; do
	killall "${app}" &> /dev/null
done

echo "Done. Note that some of these changes require a logout/restart to take effect."
